baseURL = 'http://idioptic.pages.dev/'
languageCode = 'en-us'
title = 'idioptic - simplified engineering'
author = 'Joshua Marcum'
description = 'Owner'
avatar = ''
menu_item_seperator = '|'
favicon = ''

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/xegenix"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"
